name: Iram Akhtar
favicon: null
layout_spectrum: 0.8743154443800449
typography_spectrum: 0.3803846219088882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7647721222601831
  lightness: 0.7575528654269874
  saturation: 0.70221430179663
  rhythmicContrast: 0.6849151393398643
purpose: []
