name: Iram Akhtar
favicon: null
layout_spectrum: 0.57285
typography_spectrum: 0.52697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#51565a'
    - '#110b0d'
    - '#eafafa'
    - '#c38e30'
    - '#8b2c20'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
